### ISSUE TITLE
Abbreviation incorrect for two county courts

### ISSUE THREAD

**Issue by flooie** [freelawproject/courts-db#21]
```
Florida County Court -- flacntyct
Colorado County Court -- colcntyct
```

The bluebook abbreviation for county is CTY - these two courts (have bad abbreviations) but I assume no cases yet.

**Comment by mlissner** [comment]
Changing a court ID is a big deal since it's an identifier. I hesitate to do so here unless these courts really aren't used for anything at this point.

**Comment by flooie** [comment]
We hadn't yet added those courts to CL, sorry for not making that clear.  They have been fixed in the most recent PR with florida.
