### ISSUE TITLE
What is the Circuit Court for the Western District of Florida

### ISSUE THREAD

**Issue by flooie** [freelawproject/courts-db#30]
I've come across two cases - one appears to be labeled in the Harvard as District Florida ( I think) - for the Circuit Court for the Western District of Florida.

One from 1898 

<img src="https://user-images.githubusercontent.com/6464529/133633812-d7c9dfcb-0183-42c7-b2fa-21e4a4668b37.png" width="400">

The other from 1890
<img src="https://user-images.githubusercontent.com/6464529/133634197-33b6c22b-634c-4f97-ab7c-8873bf57bf87.png" width="400">

The rub is that I can't find any references to the western district of the Florida Circuits.  So after some research - I found this long document from the Federal Judicial Center titled Creating the Federal Judicial System which was published in 1989 on the Bicentennial of the Federal Judiciary.  

The relevant part is they provided maps of the federal circuits as they progressed and were reworked by congress as State and Commonwealths joined the Union.  

In 1863

![image](https://user-images.githubusercontent.com/6464529/133636169-07aeba2f-ca3f-4708-83d6-8d7626382366.png)

1866

![image](https://user-images.githubusercontent.com/6464529/133636266-474299ad-e688-48d5-b233-a5d2df489db4.png)

1891

![image](https://user-images.githubusercontent.com/6464529/133636311-5b271fcb-2235-41a8-ac4a-d93e4e4bd0b7.png)

1929 

![image](https://user-images.githubusercontent.com/6464529/133636387-58ecb4a6-313e-478c-96e7-82a39bd286be.png)

Besides the fact that these are fascinating and drastic changes - there is no western district.  Specifically in the 1866 to 1890 time frame it is clearly North/South and the maps label Florida North/South even though there appears to be what could be an east/west division of Florida in 1929 and 1891 onward.  

The question that remains - atleast for me - is what is the western district.  How did it get into the Federal Case Reporter if it didn't exist- or is it just lost to history.  Did they refer to themselves as the western district?  What's the deal?

I would love any thoughts... @jcushman @mlissner

**Comment by flooie** [comment]
The Federal Judiciary document can be found at [here](https://www.ojp.gov/pdffiles1/Digitization/120728NCJRS.pdf).

**Comment by flooie** [comment]
Follow up: 

There is a reference in 1901 to United States Circuit Court for the District of Florida, which I have no reference for and you can see from the maps above doesn't exist.  

![d fla](https://user-images.githubusercontent.com/6464529/133642481-ad4c3283-8002-4d49-9608-b0d79082d912.png)

In this case a reading of the opinion suggests that this case occurred in the Northern District.

**Comment by jcushman** [comment]
The first case you screenshotted [starts](https://cite.case.law/f/85/570/) "In this proceeding the petitioner seeks to recover the amount of certain fees charged by him for official services as marshal for the *Northern* district of Florida, which were included in his quarterly accounts to the government, and approved by this court, and thereafter disallowed and rejected by the accounting officers of the treasury department." So at least in that instance the Northern district was misprinted as "W. D." Since the Northern district covers the western part of the state, probably fair to assume "W. D. Florida" is a misprint for Northern district in general?

**Comment by flooie** [comment]
Thanks @jcushman The same is true for another W.D. case.  The lawsuit was about a steamship that traveled between NY and 
Fernandina, Florida which with a google map search is the northeastern tip of Florida.

**Comment by gpflanagan** [comment]
Howdy y'all. Long time lurker, first time commenter. ;) Chiming in to confirm that the federal districts have indeed morphed over time. My experience is accounting for changes in the now defunct E.D. Ill. (https://en.wikipedia.org/wiki/United_States_District_Court_for_the_Eastern_District_of_Illinois). There's a fair amount of research involved in the older changes for an exhaustive approach (which led to rejiggering: "let's not do that again.")

**Comment by mlissner** [comment]
Thanks for the comment, @gpflanagan! Yes, it's quite a mess. The even harder part is how to build good websites for searching these terminated courts. Do you include their results by geography? By jurisdiction? It's a mess.

**Comment by gpflanagan** [comment]
No - just punted, they show up in textual tables and summaries but any district-specific metadata is blank.

**Comment by flooie** [comment]
@gpflanagan Thanks for chiming in and for the link on the Eastern District
