### ISSUE TITLE
Pennsylvania New Courts

### ISSUE THREAD

**Issue by flooie** [freelawproject/courts-db#40]
This is a list of the majority of the new Pennsylvania new courts, that I pulled from the Harvard courts API.

I cleaned it up slightly and added some variations already to the data set. 

Generally speaking though this is an easier ingest, with the permutations and variety of courts much nicer than the NY. Most of these courts were either combined into the Common Pleas courts in 1968 during a judicial shuffle.

ONE OFFS...
--------------------------------------------------------------------------------
Pennsylvania Arbitration Panels for Health Care
Pennsylvania Court Register of Wills
Pennsylvania Environmental Hearing Board
Pennsylvania Office of the Attorney General
Pennsylvania Board of Parole
Pennsylvania Admiralty Court
Pennsylvania Department of Education
Pennsylvania Department of Public Welfare

**Pennsylvania Department of Justice

Superior Court... ** more research needed ** appellate court
--------------------------------------------------------------------------------
Superior Court of Pennsylvania * establish in 1895

Philly Courts... ** more research needed
--------------------------------------------------------------------------------
Philadelphia Court of Nisi Prius
Philadelphia Department of Justice  ** <-- weird...
Philadelphia Election Court
Recorder of Philadelphia
Philadelphia Mayor's Court

Municipal Courts... ** more research needed
--------------------------------------------------------------------------------
Pennsylvania Municipal Court
    Philadelphia County Municipal Court|Philadelphia Municipal Court

Juvenile Courts... ** more research needed
--------------------------------------------------------------------------------
Cambria County of Juvenile Court
Delaware County Juvenile Court

Crime Courts... ** more research needed
--------------------------------------------------------------------------------
Pennsylvania County Criminal Courts
    Allegheny County Criminal Court
    Bucks County Criminal Court
    Centre County Criminal Court|Centre County Court of Criminal Court
    Fayette County Court of Criminal Court
    Lebanon County Criminal Court
    Lehigh County Criminal Court
    Luzerne County Criminal Court
    Lycoming County Criminal Court
    Mercer County Criminal Court
    Mifflin County Criminal Court
    Philadelphia County Criminal Court
    Schuylkill County Criminal Court|Schuylkill Criminal Court

Orphans Courts... ** more research needed
--------------------------------------------------------------------------------
Pennsylvania Orphans' Court | Orphans' Court
    Adams County Orphans' Court
    Allegheny County Orphans' Court
    Allegheny County Orphans' Court
    Armstrong County Orphans' Court
    Beaver County Orphans' Court
    Bedford County Orphans' Court
    Berks County Orphans' Court
    Blair County Orphans' Court
    Bradford County Orphans' Court
    Bucks County Orphans' Court
    Butler County Orphans' Court
    Cambria County Orphans' Court
    Cameron County Orphans' Court
    Carbon County Orphans' Court
    Centre County Orphans' Court
    Chester County Orphans' Court
    Clarion County Orphans' Court
    Clearfield County Orphans' Court
    Clinton County Orphans' Court
    Columbia County Orphans' Court
    Crawford County Orphans' Court
    Cumberland County Orphans' Court
    Dauphin County Orphans' Court
    Delaware County Orphans' Court
    Elk County Orphans' Court
    Erie County Orphans' Court
    Fayette County Orphans' Court
    Forest County Orphans' Court
    Franklin County Orphans' Court
    Fulton County Orphans' Court
    Greene County Orphans' Court
    Huntingdon County Orphans' Court
    Indiana County Orphans' Court
    Jefferson County Orphans' Court
    Juniata County Orphans' Court
    Lackawanna County Orphans' Court
    Lancaster County Orphans' Court
    Lawrence County Orphans' Court
    Lebanon County Orphans' Court
    Lehigh County Orphans' Court
    Luzerne County Orphans' Court
    Lycoming County Orphans' Court
    Mercer County Orphans' Court
    Mifflin County Orphans' Court
    Mongtomery County Orphans' Court
    Monroe County Orphans' Court
    Montgomery County Orphans' Court
    Montour County Orphans' Court
    Northampton County Orphans' Court
    Northumberland County Orphans' Court
    Perry County Orphans' Court
    Philadelphia County Orphans' Court
    Pike County Orphans' Court
    Schuylkill County Orphans' Court
    Snyder County Orphans' Court
    Somerset County Orphans' Court
    Sullivan County Orphans' Court
    Susquehanna County of Orphans' Court
    Susquehanna County Orphans' Court
    Tioga County Orphans' Court
    Union County Orphans' Court
    Venango County Orphans' Court
    Warren County Orphans' Court
    Washington County Orphans' Court
    Wayne County Orphans' Court
    Westmoreland County Orphans' Court
    Wyoming County Orphans' Court
    York County Orphans' Court|York County of Orphans' Court

Common Pleas... ** more research needed
--------------------------------------------------------------------------------
    Adams County of Common Pleas
    Allegheny County Commonwealth Court
    Beaver County of Common Pleas
    Clinton County of Common Pleas

Commonwealth Courts of Pennsylvania * one of two appellate courts
--------------------------------------------------------------------------------
Allegheny County Commonwealth Court  -- 1968
Philadelphia, Harrisburg and Pittsburgh*** where located...

County Court of Pennsylvania
--------------------------------------------------------------------------------
Pennsylvania County Court of Common Pleas|Pennsylvania County Court|Pennsylvania Court of Common Pleas|Court of Common Pleas|Commonwealth Court of Pennsylvania|Pennsylvania District and County Reports
    Adams County Court of Common Pleas|Adams County of Common Pleas
    Alleghany County Court of Common Pleas|Allegheny County Court|Allegheny County Court of Common Pleas|Alleghany County District Court
    Armstrong County Court of Common Pleas
    Beaver County Court of Common Pleas|Beaver County of Common Pleas
    Bedford County Court of Common Pleas
    Berks County Court of Common Pleas|Berks County Court of Common Pleas
    Blair County Court of Common Pleas
    Bradford County Court of Common Pleas
    Bucks County Court of Common Pleas|Buck County Court of Common Pleas|Buck County Court of Common Pleas
    Butler County Court of Common Pleas|Butler County Court of Common Pleas
    Cambria County Court of Common Pleas
    Cameron County Court of Common Pleas
    Carbon County Court of Common Pleas
    Centre County Court of Common Pleas
    Chester County Court of Common Pleas
    Clarion County Court of Common Pleas
    Clearfield County Court of Common Pleas
    Clinton County Court of Common Pleas|Clinton County of Common Pleas
    Columbia County Court of Common Pleas
    Crawford County Court of Common Pleas
    Cumberland County Court of Common Pleas
    Dauphin County Court of Common Pleas
    Delaware County Court of Common Pleas
    Elk County Court of Common Pleas
    Erie County Court Common Pleas|Erie County Court of Common Pleas
    Fayette County Court|Fayette County Court of Common Pleas
    Forest County Court of Common Pleas
    Franklin County Court of Common Pleas
    Fulton County Court of Common Pleas|Fulton County Court of Common Pleas
    Green County Court of Common Pleas
    Greene County Court of Common Pleas
    Harrisburg County Court of Common Pleas
    Huntingdon County Court of Common Pleas
    Indiana County Court of Common Pleas
    Jefferson County Court of Common Pleas
    Juniata County Court of Common Pleas
    Lackawanna County Court of Common Pleas
    Lancaster County Court of Common Pleas
    Lawrence County Court Common Pleas
    Lawrence County Court of Common Pleas
    Lawrence County Court of Common Pleas
    Lebanon County Court of Common Pleas
    Lehigh County Court of Common Pleas
    Luzerne County Court of Common Pleas
    Lycoming County Court of Common Pleas
    McKean County Court of Common Pleas
    Mercer County Court of Common Pleas
    Mifflin County Court of Common Pleas
    Monroe County Court of Common Pleas
    Montgomery County Court of Common Pleas
    Montour County Court of Common Pleas
    Northampton County Court of Common Pleas
    Northumberland County Court of Common Pleas
    Perry County Court of Common Pleas
    Philadelphia County Court of Common Pleas|Philadelphia County Court|Philadelphia District Court
    Pike County Court of Common Pleas
    Potter County Court of Common Pleas
    Schuylkill County Court of Common Pleas|Schuykill County Court of Common Pleas
    Snyder County Court of Common Pleas
    Somerset County Court of Common Pleas|Somerset County Court
    Sullivan County Court of Common Pleas
    Sunder County Court of Common Pleas
    Susquehanna County Court of Common Pleas
    Synder County Court of Common Pleas
    Tioga County Court of Common Pleas
    Union County Court of Common Pleas
    Venango County Court of Common Pleas
    Warren County Court of Common Pleas
    Washington County Court of Common Pleas|Washington County Court
    Wayne County Court of Common Pleas
    Westmoreland County Court of Common Pleas|Westmoreland County Court
    Wycoming County Court of Common Pleas
    Wyoming County Court of Common Pleas
    York County Court of Common Pleas

Oyer and Terminer
--------------------------------------------------------------------------------
Pennsylvania Court of Oyer and Terminer
    Adams County Court of Oyer and Terminer
    Allegheny County Court of Oyer and Terminer
    Beaver County Court of Oyer and Terminer
    Bedford County Court of Oyer and Terminer
    Berks County Court of Oyer and Terminer
    Bucks County Court of Oyer and Terminer
    Cambria County Court of Oyer and Terminer
    Carbon County Court of Oyer and Terminer
    Chester County Court of Oyer and Terminer
    Clarion County Court of Oyer and Terminer
    Columbia County Court of Oyer and Terminer
    Cumberland County Court of Oyer and Terminer
    Dauphin County Court of Oyer and Terminer
    Delaware County Court of Oyer and Terminer
    Erie County Court of Oyer and Terminer
    Fayette County Court of Oyer and Terminer
    Franklin County Court of Oyer and Terminer
    Fulton County Court of Oyer and Terminer
    Greene County Court of Oyer and Terminer
    Jefferson County Court of Oyer and Terminer
    Juniata County Court of Oyer and Terminer
    Lackawanna County Court of Oyer and Terminer
    Lancaster County Court of Oyer and Terminer
    Lawrence County Court of Oyer and Terminer
    Lebanon County Court of Oyer and Terminer
    Lehigh County Court of Oyer and Terminer
    Luzerne County Court of Oyer and Terminer
    Mercer County Court of Oyer and Terminer
    Montgomery County Court of Oyer and Terminer
    Northampton County Court of Oyer and Terminer
    Perry County Court of Oyer and Terminer
    Philadelphia County Court of Oyer and Terminer|Philadelphia Court of Oyer and Terminer
    Schuylkill County Court of Oyer and Terminer
    Somerset County Ct. Oyer & Terminer
    Susquehanna County Court of Oyer and Terminer
    Venango County Court of Oyer and Terminer
    Westmoreland County Court of Oyer and Terminer
    York County Court of Oyer and Terminer

Quarter Sessions
--------------------------------------------------------------------------------
Pennsylvania Court of Quarter Sessions ; pennctqtrsess
    Adams County Court of Quarter Sessions
    Allegheny County Court of Quarter Sessions
    Armstrong County Court of Quarter Sessions
    Beaver County Court of Quarter Sessions
    Bedford County Court of Quarter Sessions
    Berks County Court of Quarter Sessions
    Blair County Court of Quarter Sessions
    Bradford County Court of Quarter Sessions
    Bucks County Court of Quarter Sessions
    Butler County Court of Quarter Sessions
    Cambria County Court of Quarter Sessions
    Cameron County Court of Quarter Sessions
    Carbon County Court of Quarter Sessions
    Centre County Court of Quarter Sessions
    Chester County Court of Quarter Sessions
    Clarion County Court of Quarter Sessions
    Clearfield County Court of Quarter Sessions
    Clinton County Court of Quarter Sessions
    Columbia County Court of Quarter Sessions
    Crawford County Court of Quarter Sessions
    Cumberland County Court of Quarter Sessions
    Dauphin County Court of Quarter Sessions
    Delaware County Court of Quarter Sessions
    Elk County Court of Quarter Sessions
    Erie County Court of Quarter Sessions
    Fayette County Court of Quarter Sessions
    Franklin County Court of Quarter Sessions
    Fulton County Court of Quarter Sessions
    Greene County Court of Quarter Sessions
    Huntingdon County Court of Quarter Sessions
    Indiana County Court of Quarter Sessions
    Jefferson County Court of Quarter Sessions
    Juniata County Court of Quarter Sessions
    Lackawanna County Court of Quarter Sessions
    Lancaster County Court of Quarter Sessions
    Lawrence County Court of Quarter Sessions|Lawrence County Court Quarter Sessions
    Lebanon County Court of Quarter Sessions
    Lehigh County Court of Quarter Sessions
    Luzerne County Court of Quarter Sessions
    Lycoming County Court of Quarter Sessions
    McKean County Court of Quarter Sessions
    Mercer County Court of Quarter Sessions
    Mifflin County Court of Quarter Sessions
    Monroe County Court of Quarter Sessions
    Montgomery County Court of Quarter Sessions
    Montour County Court of Quarter Sessions
    Northampton County Court of Quarter Sessions
    Northumberland County Court of Quarter Sessions
    Perry County Court of Quarter Sessions
    Philadelphia Co. Court of Quarter Sessions
    Philadelphia County Court of Quarter Sessions
    Pike County Court of Quarter Sessions
    Potter County Court of Quarter Sessions
    Schuylkill County Court of Quarter Sessions
    Snyder County Court of Quarter Sessions
    Somerset County Court of Quarter Sessions
    Sullivan County Court of Quarter Sessions
    Susquehanna County Court of Quarter Sessions
    Tioga County Court of Quarter Sessions
    Union County Court of Quarter Sessions
    Venango County Court of Quarter Sessions
    Warren County Court of Quarter Sessions
    Washington County Court of Quarter Sessions
    Wayne County Court of Quarter Sessions
    Westmoreland County Court of Quarter Sessions
    Wyoming County Court of Quarter Sessions
    York County Court of Quarter Sessions

**Comment by flooie** [comment]
I thought I would include this completely normal, and not at all conspiracy generating visual from the Judiciary of Pennsylvania.  

https://www.pacourts.us/learn

<img width="838" alt="Screen Shot 2022-02-11 at 4 24 22 PM" src="https://user-images.githubusercontent.com/6464529/153672286-780c1c0e-f927-45cb-b069-936d54ae41d3.png">

**Comment by mlissner** [comment]
Well, I wasted five minutes trying to put an eyeball at the top of that pyramid, but my Gimp skills are too terrible, so we all dodged that bullet. 

In the meantime, this is a great summary, thank you.
