### ISSUE TITLE
Ohio Courts

### ISSUE THREAD

**Issue by flooie** [freelawproject/courts-db#41]
Harvard has a ton of new Ohio courts.
The system is pretty organized, and there don't appear to be a lot of changes over time. Here is the list of unique courts in the Harvard Database.  

There are clearly some duplicates but there are some oddities.  

Circuit courts appear to no longer exist, they use "area" courts when municipal courts dont cover the entire county (which is very strange).  I assume this means unincorporated areas.

![judSysStructSimp](https://user-images.githubusercontent.com/6464529/153895878-ba1ee103-74b2-42d1-a2b2-08a4b1c0bf57.jpg)

The OH Supreme Court website was helpful enough [Judicial Wesbite](https://www.supremecourt.ohio.gov/judsystem/).

Superior ** more research needed
--------------------------------
Cincinnati Superior Court

Probate
--------------------------------
Ashtabula County Probate Court
Ohio Probate Court
Ohio Probate Court of Franklin County
Allen County Probate Court
Ashtabula County Probate Court
Auglaize County Probate Court
Belmont County Probate Court
Butler County Probate Court
Champaign County Probate Court
Clark County Probate Court
Clarke County Probate Court
Clermont County Probate Court
Clinton County Probate Court
Columbiana County Probate Court
Cuyahoga County Probate Court
Darke County Probate Court
Erie County Probate Court
Fairfield County Probate Court
Fayette County Probate Court
Franklin County Probate Court
Franklin County Probate Court
Fulton County Probate Court
Geauga County Probate Court
Greene County Probate Court
Hamilton County Probate Court
Hancock County Probate Court
Hardin County Probate Court
Harrison County Probate Court
Henry County Probate Court
Highland County Probate Court
Huron County Probate Court
Jackson County Probate Court
Jefferson County Probate Court
Knox County Probate Court
Lake County Probate Court
Licking County Probate Court
Lorain County Probate Court
Lucas County Probate Court
Madison County Probate Court
Mahoning County Probate Court
Marion County Probate Court
Meigs County Probate Court
Mercer County Probate Court
Miami County Probate Court
Montgomery County Probate Court
Morgan County Probate Court
Muskingum County Probate Court
Noble County Probate Court
Ohio Probate Court
Ohio Probate Court of Franklin County
Perry County Probate Court
Pike County Probate Court
Portage County Probate Court
Preble County Probate Court
Probate Court
Putnam County Probate Court
Ross County Probate Court
Sandusky County Probate Court
Scioto County Probate Court
Seneca County Probate Court
Shelby County Probate Court
Stark County Probate Court
Summit County Probate Court
Trumbull County Probate Court
Tuscarawas County Probate Court
Union County Probate Court
Van Wert County Probate Court
Warren County Probate Court
Washington County Probate Court
Wayne County Probate Court

Municipal
--------------------------------
Akron Municipal Court
Athens County Municipal Court
Criminal Branch Municipal Court
Dayton City Municipal Court
Dayton County Municipal Court
Ohio Municipal Court
Ohio Municipal Court, Cleveland
Ohio Municipal Court, Cleveland. Cuyahoga County
Ohio Municipal Court of Dayton
Akron Municipal Court
Akron Municipal Court.
Ashland Municipal Court
Ashtabula Municipal Court
Athens County Municipal Court
Auglaize County Municipal Court
Avon Lake Municipal Court
Barberton Municipal Court
Bedford Municipal Court
Bellefontaine Municipal Court
Berea Municipal Court
Bowling Green County Municipal Court
Bowling Green Municipal Court
Canton Municipal Court
Celina Municipal Court
Chardon Municipal Court
Chillicothe Municipal Court
Cincinnati Municipal Court
Circleville Municipal Court
City of Cleveland Municipal Court
City of Columbus Municipal Court
City of Dayton Municipal Court
Clark County Municipal Court
Clermont County Municipal Court
Clermont Municipal Court
Cleveland County Municipal Court
Cleveland Heights Municipal Court
Cleveland Municipal Court
Columbus Municipal Court
Crawford County Municipal Court
Criminal Branch Municipal Court
Cuyahoga County Municipal Court
Cuyahoga Falls Municipal Court
Cuyahoga Falls Municipal Court
Cuyahoga Municipal Court
Darke County Municipal Court
Dayton City Municipal Court
Dayton County Municipal Court
Dayton Municipal Court
East Liverpool Municipal Court
Elyria Municipal Court
Euclid City Municipal Court
Euclid Municipal Court
Findlay Municipal Court
Fostoria Municipal Court
Franklin County Municipal Court
Franklin Municipal Court
Fremont Municipal Court
Gallipolis Municipal Court
Girard Municipal Court
Hamilton County Municipal Court
Hamilton Municipal Court
Highland County Municipal Court
Hocking County Municipal Court
Kettering Municipal Court
Lakewood Municipal Court
Lancaster Municipal Court
Lawrence County Municipal Court
Licking County Municipal Court
Lima Municipal Court
Lorain Municipal Court
Lucas County Municipal Court
Mansfield Municipal Court
Marion County Municipal Court
Marion Municipal Court
Marysville Municipal Court
Massillon Municipal Court
Maumee Municipal Court
Medina Municipal Court
Miamisburg Municipal Court
Middletown Municipal Court
Morrow County Municipal Court
Municipal Court of Vandalia
New Philadelphia Municipal Court
Newton Falls Municipal Court
Oberlin Municipal Court
Ohio Municipal Court
Ohio Municipal Court, Cleveland
Ohio Municipal Court, Cleveland. Cuyahoga County
Ohio Municipal Court of Dayton
Parma Municipal Court
Perrysburg Municipal Court
Piqua Municipal Court
Portage County Municipal Court
Port Clinton Municipal Court
Portsmouth Municipal Court
Ravenna Municipal Court
Rocky River Municipal Court
Shaker Heights Municipal Court
Sidney Municipal Court
South Euclid Municipal Court
Springfield Municipal Court
Struthers Municipal Court
Summit County Municipal Court
Sylvania Municipal Court
Tiffin Municipal Court
Toledo Municipal Court
Trumbull County Municipal Court
Upper Sandusky Municipal Court
Vandalia Municipal Court
Van Wert County Municipal Court
Van Wert Municipal Court
Wadsworth Municipal Court
Warren County Municipal Court
Wayne County Municipal Court
Willoughby Municipal Court
Xenia Municipal Court
Zanesville Municipal Court

Criminal
--------------------------------
Criminal Branch Municipal Court
Canton Criminal Court
Criminal Branch Municipal Court

Police
--------------------------------
Cincinnati Police Court
Cleveland Police Court
Columbus Police Court

Appeals
--------------------------------
Ashtabula County Court of Appeals
Butler County Court of Appeals
Clinton County Court of Appeals
Court of Appeals of Ohio, Eighth District, Cuyahoga County
Court of Appeals of Ohio, Eleventh District, Ashtabula County
Court of Appeals of Ohio, Eleventh District, Geauga County
Court of Appeals of Ohio, Eleventh District, Lake County
Court of Appeals of Ohio, Eleventh District, Portage County
Court of Appeals of Ohio, Eleventh District, Trumbull County
Court of Appeals of Ohio, Fifth District, Ashland County
Court of Appeals of Ohio, Fifth District, Coshocton County
Court of Appeals of Ohio, Fifth District, Delaware County
Court of Appeals of Ohio, Fifth District, Fairfield County
Court of Appeals of Ohio, Fifth District, Guernsey County
Court of Appeals of Ohio, Fifth District, Holmes County
Court of Appeals of Ohio, Fifth District, Knox County
Court of Appeals of Ohio, Fifth District, Licking County
Court of Appeals of Ohio, Fifth District, Morgan County
Court of Appeals of Ohio, Fifth District, Morrow County
Court of Appeals of Ohio, Fifth District, Muskingum County
Court of Appeals of Ohio, Fifth District, Richland County
Court of Appeals of Ohio, Fifth District, Stark County
Court of Appeals of Ohio, Fifth District, Tuscarawas County
Court of Appeals of Ohio, First District, Hamilton County
Court of Appeals of Ohio, Fourth District, Adams County
Court of Appeals of Ohio, Fourth District, Athens County
Court of Appeals of Ohio, Fourth District, Gallia County
Court of Appeals of Ohio, Fourth District, Highland County
Court of Appeals of Ohio, Fourth District, Hocking County
Court of Appeals of Ohio, Fourth District, Jackson County
Court of Appeals of Ohio, Fourth District, Lawrence County
Court of Appeals of Ohio, Fourth District, Meigs County
Court of Appeals of Ohio, Fourth District, Pickaway County
Court of Appeals of Ohio, Fourth District, Pike County
Court of Appeals of Ohio, Fourth District, Ross County
Court of Appeals of Ohio, Fourth District, Scioto County
Court of Appeals of Ohio, Fourth District, Vinton County
Court of Appeals of Ohio, Fourth District, Washington County
Court of Appeals of Ohio, Ninth District, Lorain County
Court of Appeals of Ohio, Ninth District, Medina County
Court of Appeals of Ohio, Ninth District, Summit County
Court of Appeals of Ohio, Ninth District, Wayne County
Court of Appeals of Ohio, Second District, Champaign County
Court of Appeals of Ohio, Second District, Clark County
Court of Appeals of Ohio, Second District, Darke County
Court of Appeals of Ohio, Second District, Greene County
Court of Appeals of Ohio, Second District, Miami County
Court of Appeals of Ohio, Second District, Montgomery County
Court of Appeals of Ohio, Seventh District, Belmont County
Court of Appeals of Ohio, Seventh District, Carroll County
Court of Appeals of Ohio, Seventh District, Columbiana County
Court of Appeals of Ohio, Seventh District, Harrison County
Court of Appeals of Ohio, Seventh District, Jefferson County
Court of Appeals of Ohio, Seventh District, Mahoning County
Court of Appeals of Ohio, Seventh District, Monroe County
Court of Appeals of Ohio, Seventh District, Noble County
Court of Appeals of Ohio, Sixth District, Erie County
Court of Appeals of Ohio, Sixth District, Fulton County
Court of Appeals of Ohio, Sixth District, Huron County
Court of Appeals of Ohio, Sixth District, Lucas County
Court of Appeals of Ohio, Sixth District, Ottawa County
Court of Appeals of Ohio, Sixth District, Sandusky County
Court of Appeals of Ohio, Sixth District, Williams County
Court of Appeals of Ohio, Sixth District, Wood County
Court of Appeals of Ohio, Tenth District, Franklin County
Court of Appeals of Ohio, Third District, Allen County
Court of Appeals of Ohio, Third District, Auglaize County
Court of Appeals of Ohio, Third District, Crawford County
Court of Appeals of Ohio, Third District, Defiance County
Court of Appeals of Ohio, Third District, Hancock County
Court of Appeals of Ohio, Third District, Hardin County
Court of Appeals of Ohio, Third District, Henry County
Court of Appeals of Ohio, Third District, Logan County
Court of Appeals of Ohio, Third District, Marion County
Court of Appeals of Ohio, Third District, Mercer County
Court of Appeals of Ohio, Third District, Paulding County
Court of Appeals of Ohio, Third District, Putnam County
Court of Appeals of Ohio, Third District, Seneca County
Court of Appeals of Ohio, Third District, Shelby County
Court of Appeals of Ohio, Third District, Union County
Court of Appeals of Ohio, Third District, Van Wert County
Court of Appeals of Ohio, Third District, Wyandot County
Court of Appeals of Ohio, Twelfth District, Brown County
Court of Appeals of Ohio, Twelfth District, Butler County
Court of Appeals of Ohio, Twelfth District, Clermont County
Court of Appeals of Ohio, Twelfth District, Clinton County
Court of Appeals of Ohio, Twelfth District, Fayette County
Court of Appeals of Ohio, Twelfth District, Madison County
Court of Appeals of Ohio, Twelfth District, Preble County
Court of Appeals of Ohio, Twelfth District, Warren County
Cuyahoga County Court of Appeals
Delaware County Court of Appeals
Franklin County Court of Appeals
Greene County Court of Appeals
Guernsey County Court of Appeals
Guernsey County Court of Appeals
Hamilton County Court of Appeals
Harrison County Court of Appeals
Huron County Court of Appeals
Jefferson County Court of Appeals
Knox County Court of Appeals
Lawrence County Court of Appeals
Licking County Court of Appeals
Lucas County Court of Appeals
Mahoning County Court of Appeals
Ohio Board of Tax Appeals
Ohio Court of Appeals
Stark County Court of Appeals
Summit County Court of Appeals
United States Court of Appeals for the District of Columbia
United States Court of Appeals for the Sixth Circuit
Wayne County Court of Appeals
Wood County Court of Appeals

Federal
---------------------------
United States Court of Appeals for the District of Columbia
United States Court of Appeals for the Sixth Circuit

One Offs
---------------------------
Ohio Board of Commissioners on the Unauthorized Practice of Law                                      []
Ohio Civil Rights Commission                                                                         ['ohiocivright']
Ohio Court of Nisi Prius                                                                             []
Ohio Federal Communications Commission                                                               []
Ohio Public Utilities Commission                                                                     ['ohiopuc']
Ohio State Racing Commission
Public Utilities Commission                                                                          []

Circuit
--------------------------------
Auglaize County Circuit Court
Ohio Circuit Court
United States Court of Appeals for the Sixth Circuit
Adams Circuit Court
Adams County Circuit Court
Allen Circuit Court
Allen County Circuit Court
Ashland Circuit Court
Ashland County Circuit Court
Ashtabula Circuit Court
Ashtabula County Circuit Court
Athens Circuit Court
Auglaize Circuit Court
Auglaize County Circuit Court
Belmont Circuit Court
Belmont County Circuit Court
Brown Circuit Court
Brown County Circuit Court
Butler Circuit Court
Butler County Circuit Court
Carroll Circuit Court
Carroll County Circuit Court
Champaign Circuit Court
Champaign County Circuit Court
Clark Circuit Court
Clark County Circuit Court
Clarke Circuit Court
Clarke County Circuit Court
Clermont Circuit Court
Clermont County Circuit Court
Clinton Circuit Court
Clinton County Circuit Court
Columbiana Circuit Court
Columbiana County Circuit Court
Coshocton Circuit Court
Coshocton County Circuit Court
Crawford Circuit Court
Crawford County Circuit Court
Cuyahoga Circuit Court
Cuyahoga County Circuit Court
Darke Circuit Court
Darke County Circuit Court
Defiance Circuit Court
Defiance County Circuit Court
Delaware Circuit Court
Delaware County Circuit Court
Erie Circuit Court
Erie County Circuit Court
Fairfield Circuit Court
Fairfield County Circuit Court
Fayette Circuit Court
Fayette County Circuit Court
Franklin Circuit Court
Franklin County Circuit Court
Fulton Circuit Court
Fulton County Circuit Court
Geauga Circuit Court
Geauga County Circuit Court
Greene Circuit Court
Greene County Circuit Court
Guernsey Circuit Court
Guernsey County Circuit Court
Hamilton Circuit Court
Hamilton County Circuit Court
Hancock Circuit Court
Hancock County Circuit Court
Hancook Circuit Court
Hardin Circuit Court
Hardin County Circuit Court
Harrison Circuit Court
Harrison County Circuit Court
Henry Circuit Court
Henry County Circuit Court
Highland Circuit Court
Highland County Circuit Court
Holmes Circuit Court
Holmes County Circuit Court
Huron Circuit Court
Huron County Circuit Court
Jackson Circuit Court
Jackson County Circuit Court
Jefferson Circuit Court
Jefferson County Circuit Court
Knox County Circuit Court
Lake County Circuit Court
Lawrence Circuit Court
Lawrence County Circuit Court
Licking Circuit Court
Licking County Circuit Court
Logan Circuit Court
Logan County Circuit Court
Lorain Circuit Court
Lorain County Circuit Court
Lucas Circuit Court
Lucas County Circuit Court
Madison Circuit Court
Madison County Circuit Court
Mahoning Circuit Court
Mahoning County Circuit Court
Marion Circuit Court
Marion County Circuit Court
Medina Circuit Court
Medina County Circuit Court
Meigs Circuit Court
Meigs County Circuit Court
Mercer Circuit Court
Mercer County Circuit Court
Miami Circuit Court
Miami County Circuit Court
Monroe Circuit Court
Monroe County Circuit Court
Montgomery Circuit Court
Montgomery County Circuit Court
Morgan Circuit Court
Morgan County Circuit Court
Morrow Circuit Court
Morrow County Circuit Court
Muskingum Circuit Court
Muskingum County Circuit Court
Noble Circuit Court
Noble County Circuit Court
Ohio Circuit Court
Ottawa Circuit Court
Ottawa County Circuit Court
Paulding Circuit Court
Paulding County Circuit Court
Perry Circuit Court
Perry County Circuit Court
Pickaway Circuit Court
Pickaway County Circuit Court
Pike Circuit Court
Pike County Circuit Court
Portage Circuit Court
Portage County Circuit Court
Preble Circuit Court
Preble County Circuit Court
Putnam Circuit Court
Putnam County Circuit Court
Richland Circuit Court
Richland County Circuit Court
Ross Circuit Court
Ross County Circuit Court
Sandusky Circuit Court
Sandusky County Circuit Court
Scioto Circuit Court
Scioto County Circuit Court
Seneca Circuit Court
Seneca County Circuit Court
Shelby Circuit Court
Shelby County Circuit Court
Stark Circuit Court
Stark County Circuit Court
Summit Circuit Court
Summit County Circuit Court
Taggart Circuit Court
Trumbull Circuit Court
Trumbull County Circuit Court
Tuscarawas Circuit Court
Tuscarawas County Circuit Court
Union County Circuit Court
Van Wert Circuit Court
Van Wert County Circuit Court
Vinton County Circuit Court
Warren Circuit Court
Warren County Circuit Court
Wayne Circuit Court
Wayne County Circuit Court
Williams Circuit Court
Williams County Circuit Court
Wood Circuit Court
Wood County Circuit Court
Wyandot Circuit Court
Wyandot County Circuit Court
Wyandotte County Circuit Court

Area
--------------------------------
Area One County Court

Insolvency
--------------------------------
Hamilton County Court of Insolvency
Cuyahoga County Court of Insolvency
Hamilton County Court of Insolvency

District?
--------------------------------
Could district refer to court of appeals ...x district?
Lucas County District Court

Juvenile
--------------------------------
Allen County Juvenile Court
Allen County Juvenile Court
Columbiana County Juvenile Court
Cuyahoga County Juvenile Court
Greene County Juvenile Court
Hamilton County Juvenile Court
Huron County Juvenile Court
Juvenile Court, Columbiana County
Licking County Juvenile Court
Lucas County Juvenile Court
Marion County Juvenile Court
Muskingum County Juvenile Court
Noble County Juvenile Court
Preble County Juvenile Court
Tuscarawas County Juvenile Court
Warren County Juvenile Court
Wayne County Juvenile Court

Common Pleas 
--------------------------------
Athens County Court of Common Pleas
Athens County Court of Common Pleas
Ohio Common Pleas
Ohio Court of Common Pleas
Adams County Court of Common Pleas
Allen County Court of Common Pleas
Ashland County Court of Common Pleas
Ashtabula County Court of Common Pleas
Athens County Court of Common Pleas
Auglaize County Court of Common Pleas
Belmont County Court of Common Pleas
Boss County Court of Common Pleas
Brown County Court of Common Pleas
Butler County Court of Common Pleas
Carroll County Court of Common Pleas
Champaign County Court of Common Pleas
Clark County Court of Common Pleas
Clarke County Court of Common Pleas
Clarke Court of Common Pleas
Clermont County Court of Common Pleas
Clinton County Court of Common Pleas
Clinton County Court of Common Pleas
Columbiana County Court of Common Pleas
Coshocton County Court of Common Pleas
Court of Common Pleas
Court of Common Pleas of Ohio, Clermont County, Ohio
Court of Common Pleas of Ohio, Franklin County, Civil Division
Court of Common Pleas of Ohio, Hamilton County
Crawford County Court of Common Pleas
Crawford County Court of Common Pleas
Crawford County Court of Common Pleas
Cuyahoga County Common Pleas Court
Cuyahoga County Court of Common Pleas
Cuyahoga County Court of Common Pleas
Darke County Court of Common Pleas
Defiance County Court of Common Pleas
Delaware County Court of Common Pleas
Delaware County Court of Common Pleas
Erie County Court of Common Pleas
Erie County Court of Common Pleas
Fairfield County Court of Common Pleas
Fayette County Court of Common Pleas
Fayette County Court of Common Pleas
Fayette County Court of Common Pleas
Franklin County Court of Common Pleas
Franklin County Court of Common Pleas
Fulton County Court of Common Pleas
Fulton County Court of Common Pleas
Galia County Court of Common Pleas
Gallia County Court of Common Pleas
Geauga County Court of Common Pleas
Green County Court of Common Pleas
Greene County Court of Common Pleas
Greene County Court of Common Pleas
Guernsey County Court of Common Pleas
Hamilton County Court of Common Pleas
Hancock County Court of Common Pleas
Hardin County Court of Common Pleas
Harrison County Court of Common Pleas
Harrison County Court of Common Pleas
Henry County Court of Common Pleas
Highland County Court of Common Pleas
Hocking County Court of Common Pleas
Holmes County Court of Common Pleas
Huron County Court of Common Pleas
Jackson County Court of Common Pleas
Jefferson County Court of Common Pleas
Jefferson County Court of Common Pleas
Knox County Court of Common Pleas
Lake County Court of Common Pleas
Lawrence County Common Pleas Court
Lawrence County Court of Common Pleas
Licking County Court of Common Pleas
Logan County Court of Common Pleas
Lorain County Court of Common Pleas
Lucas County Court of Common Pleas
Madison County Court of Common Pleas
Mahoning County Court of Common Pleas
Marion County Court of Common Pleas
Medina County Court of Common Pleas
Meigs County Court of Common Pleas
Mercer County Court of Common Pleas
Miami County Court of Common Pleas
Monroe County Court of Common Pleas
Montgomery County Court of Common Pleas
Morgan County Court of Common Pleas
Morrow County Court of Common Pleas
Muskingum County Court of Common Pleas
Noble County Court of Common Pleas
Ohio Common Pleas
Ohio Court of Common Pleas
Ottawa County Court of Common Pleas
Paulding County Court of Common Pleas
Pickaway County Court of Common Pleas
Pike County Court of Common Pleas
Portage County Court of Common Pleas
Preble County Court of Common Pleas
Putnam County Court of Common Pleas
Richland County Court of Common Pleas
Ross County Court of Common Pleas
Sandusky County Court of Common Pleas
Scioto County Court of Common Pleas
Seneca County Court of Common Pleas
Shelby County Court of Common Pleas
Stark County Court of Common Pleas
Summit County Court of Common Pleas
Tascarawas County Court of Common Pleas
Trumbull County Court of Common Pleas
Tuscarawas County Court of Common Pleas
Union County Court of Common Pleas
Van Wert County Court of Common Pleas
Vinton County Court of Common Pleas
Warren County Court of Common Pleas
Washington County Court of Common Pleas
Wayne County Court of Common Pleas
Williams County Court of Common Pleas
Wood County Court of Common Pleas
Wyandot County Court of Common Pleas

**Comment by mlissner** [comment]
Wow, wow, wow, this is great. @satsuki-chan and @albertisfu, if y'all want to better understand what Bill means when he says he's adding courts to the courts-db, this is a good example.

**Comment by flooie** [comment]
Thanks @mlissner
