### ISSUE TITLE
Georgia Superior Courts level is weird

### ISSUE THREAD

**Issue by anseljh** [freelawproject/courts-db#7]
For the Georgia Superior Courts (`gasuperct`), the `level` is weird. Is this correct? It doesn't seem to be. It looks like the correct intermediate appellate court above the Georgia Superior Courts is the [Georgia Court of Appeals](https://www.gaappeals.us/) (`gactapp`).

```
"level": "gjc & iac"
```

**Comment by flooie** [comment]
Yes- it certainly is.  That certainly came from using a string in a field that should've been something else I suspect.  

After all this time I think its obvious that level should be the primary purpose of the court.  In this case I think superior courts are generally trial courts (even though they may hear some appeals from limited jurisdiction municipal courts)

I would be happy to hear your thoughts though @anseljh

**Comment by flooie** [comment]
This was weird, and has been updated to the primary purpose of the court.
