### ISSUE TITLE
Jurisdiction typos

### ISSUE THREAD

**Issue by warrenronsiek** [freelawproject/courts-db#75]
The jurisdiction key is has minor inconsistencies. In a couple cases its an array, in other cases it doesn't follow the two letter abbreviation format. I have a branch to fix this, but I don't have permission to push. Would appreciate commit permissions.

**Comment by mlissner** [comment]
Hi Warren. Thanks for digging into this. 

If you made a branch in your fork, you should be able to create a Pull Request?
