### ISSUE TITLE
Notes field

### ISSUE THREAD

**Issue by warrenronsiek** [freelawproject/courts-db#79]
I'd like to add an optional notes field that contains explanations/descriptions/references, links etc. to source material. 

I'm going through a lot of these courts, and it would be helpful to have some notation or explanation for why certain properties are what they are. If I make changes, I'd like to leave a record of why I changed it. 

So many of these things are opaque and on some kind of decision boundary that are not obvious. 

Any objection?

**Comment by warrenronsiek** [comment]
realized this field already exists!

**Comment by mlissner** [comment]
It does, but it's not documented. I'll fix that.
