### ISSUE TITLE
Assign ids for missouri court of appeals district courts

### ISSUE THREAD

**Issue by quevon24** [freelawproject/courts-db#92]
Which ids should we assign for missing district courts in courts-db?

- Missouri Court of Appeals, Western District
- Missouri Court of Appeals, Eastern District
- Missouri Court of Appeals, Southern District

Taking a look at courts-db it generally adds wd, sd or ed to identify the district, for example: miwd (United States District Court For The Western Division of Michigan), mssd (Southern District of Mississippi) or illinoised (United States District Court for the Eastern District of Illinois)

I also took a look to uscourts page, and they usually do the same, for example: [caed.uscourts.gov](http://caed.uscourts.gov/), [alsd.uscourts.gov](http://alsd.uscourts.gov/)

But in some cases that doesn't apply, for example with: [www.are.uscourts.gov/](http://www.are.uscourts.gov/) or [www.mow.uscourts.gov](http://www.mow.uscourts.gov/)

I think these should be the ids:

- Missouri Court of Appeals, Western District (moctappwd)
- Missouri Court of Appeals, Eastern District (moctapped)
- Missouri Court of Appeals, Southern District (moctappsd)

@flooie

**Comment by mlissner** [comment]
Bill has done a lot of this, so I'll steer mostly clear, but [SALI](https://sali.org) has gotten a lot more popular since we last created IDs for courts, so it might be worth a quick look at it.

**Comment by quevon24** [comment]
I took a look at SALI but could't find the labels for the court of appeals district courts, only for the court of appeals: http://lmss.sali.org/R6618c897B273F9Da2aBD7dd and it is the same that we currently have in courts-db: moctapp

For us district courts they use these suffixes for the western and eastern districts: wd and ed

- mowd (District Court, W.D. Missouri) http://lmss.sali.org/R7C6fc65AEd87E261b305daf
- moed (District Court, E.D. Missouri)  http://lmss.sali.org/R2B3b98C672de58E41e84719
- no trace of the southern district in SALI

The docket numbers of each district court of appeals contain these prefixes: ED, WD, and SD, perhaps we can use them.

- ED111751 (https://www.courts.mo.gov/file.jsp?id=208220)
- WD86436 (https://www.courts.mo.gov/file.jsp?id=208173)
- SD37744 (https://www.courts.mo.gov/file.jsp?id=208254)

**Comment by mlissner** [comment]
Yeah, SALI is a monster, but thanks for digging into it. We'll need a SALI expert around here eventually anyway. I leave final analysis to @flooie when he gets a moment!

**Comment by gpflanagan** [comment]
I'm no SALI expert. I am absolutely "SALI-curious" when it comes to coding courts.
